/** Closed experiment flags. Not current R&D selection. */
export const ARCHIVED_REFLECTIVE_QUESTION_EXPERIMENT_ENV_FLAGS = [
  'REFLECTIVE_QUESTION_EXPERIMENT',
  'REFLECTIVE_QUESTION_WITNESSED_OPENING',
  'REFLECTIVE_QUESTION_SURGICAL_ATTENTION',
  'REFLECTIVE_QUESTION_RELATION_ELIGIBILITY_ABLATION',
  'REFLECTIVE_QUESTION_SELECTION_LANGUAGE_DECOUPLING',
  'REFLECTIVE_QUESTION_FREEZE_VALIDATION',
  'REFLECTIVE_QUESTION_LANGUAGE_OPERATOR',
  'REFLECTIVE_QUESTION_DEVELOPMENT_STRESS',
  'REFLECTIVE_QUESTION_LANGUAGE_OPERATOR_CANDIDATE_B',
  'REFLECTIVE_QUESTION_LIVE_BENCHMARK',
  'ONEIROS_POST_READING_INVITER_GATE1_COST_APPROVED',
  'ONEIROS_POST_JUNGIAN_INVITER_V2_GATE1_COST_APPROVED',
  'ONEIROS_EDITORIAL_ARC_GATE1_COST_APPROVED',
  'ONEIROS_POST_JUNGIAN_INVITER_V2_LOCAL_APPROVED',
] as const;
