const fs = require('fs');
const path = require('path');
const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withAppDelegate,
  withDangerousMod,
} = require('expo/config-plugins');

const FULL_BACKUP_RESOURCE = '@xml/oneiros_backup_rules';
const DATA_EXTRACTION_RESOURCE = '@xml/oneiros_data_extraction_rules';

const fullBackupRules = `<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
  <exclude domain="sharedpref" path="SecureStore" />
  <exclude domain="file" path="voice_pending/" />
</full-backup-content>
`;

const dataExtractionRules = `<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="sharedpref" path="SecureStore" />
    <exclude domain="file" path="voice_pending/" />
  </cloud-backup>
  <device-transfer>
    <exclude domain="sharedpref" path="SecureStore" />
    <exclude domain="file" path="voice_pending/" />
  </device-transfer>
</data-extraction-rules>
`;

const iosHelper = `  // @generated by withVoicePendingStoragePrivacy
  private func prepareVoicePendingDirectory() {
    do {
      let documents = try FileManager.default.url(
        for: .documentDirectory,
        in: .userDomainMask,
        appropriateFor: nil,
        create: true
      )
      var pendingDirectory = documents.appendingPathComponent("voice_pending", isDirectory: true)
      try FileManager.default.createDirectory(
        at: pendingDirectory,
        withIntermediateDirectories: true
      )
      var resourceValues = URLResourceValues()
      resourceValues.isExcludedFromBackup = true
      try pendingDirectory.setResourceValues(resourceValues)

      // Clips created by versions before voice_pending/ lived directly under
      // Documents. Keep those recoverable files out of backups until normal
      // queue delivery or seven-day cleanup removes them.
      let legacyVoicePattern = #"^voice-[0-9]+-[A-Za-z0-9]+(?:\\.[A-Za-z0-9]{2,5}|\\.inbox\\.json)$"#
      let documentFiles = try FileManager.default.contentsOfDirectory(
        at: documents,
        includingPropertiesForKeys: nil,
        options: [.skipsHiddenFiles]
      )
      for fileURL in documentFiles where fileURL.lastPathComponent.range(
        of: legacyVoicePattern,
        options: .regularExpression
      ) != nil {
        do {
          var legacyFileURL = fileURL
          var legacyResourceValues = URLResourceValues()
          legacyResourceValues.isExcludedFromBackup = true
          try legacyFileURL.setResourceValues(legacyResourceValues)
        } catch {
          NSLog("[Oneiros] Failed to exclude a legacy voice clip from backup")
        }
      }
    } catch {
      NSLog("[Oneiros] Failed to prepare backup-excluded voice pending directory")
    }
  }
`;

function withVoicePendingStoragePrivacy(config) {
  config = withAndroidManifest(config, (androidConfig) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidConfig.modResults);
    application.$['android:fullBackupContent'] = FULL_BACKUP_RESOURCE;
    application.$['android:dataExtractionRules'] = DATA_EXTRACTION_RESOURCE;
    return androidConfig;
  });

  config = withDangerousMod(config, ['android', async (androidConfig) => {
    const xmlDirectory = path.join(
      androidConfig.modRequest.platformProjectRoot,
      'app',
      'src',
      'main',
      'res',
      'xml',
    );
    fs.mkdirSync(xmlDirectory, { recursive: true });
    fs.writeFileSync(path.join(xmlDirectory, 'oneiros_backup_rules.xml'), fullBackupRules);
    fs.writeFileSync(path.join(xmlDirectory, 'oneiros_data_extraction_rules.xml'), dataExtractionRules);
    return androidConfig;
  }]);

  config = withAppDelegate(config, (iosConfig) => {
    if (iosConfig.modResults.language !== 'swift') {
      throw new Error('Oneiros voice pending storage privacy requires a Swift AppDelegate');
    }
    let source = iosConfig.modResults.contents;
    if (!source.includes('prepareVoicePendingDirectory()')) {
      const launchAnchor = '    bindReactNativeFactory(factory)';
      if (!source.includes(launchAnchor)) {
        throw new Error('Could not find the AppDelegate launch anchor for voice storage privacy');
      }
      source = source.replace(launchAnchor, `${launchAnchor}\n    prepareVoicePendingDirectory()`);
    }
    const helperMarker = '  // @generated by withVoicePendingStoragePrivacy';
    const classEndAnchor = '\n  // Linking API';
    if (!source.includes(classEndAnchor)) {
      throw new Error('Could not find the AppDelegate helper anchor for voice storage privacy');
    }
    if (source.includes(helperMarker)) {
      // Replace the entire generated helper so plugin upgrades also update an
      // existing local native project, not only a clean EAS prebuild.
      const helperStart = source.indexOf(helperMarker);
      const helperEnd = source.indexOf(classEndAnchor, helperStart);
      if (helperEnd < 0) {
        throw new Error('Could not replace the generated voice storage privacy helper');
      }
      source = `${source.slice(0, helperStart)}${iosHelper}${source.slice(helperEnd)}`;
    } else {
      source = source.replace(classEndAnchor, `\n${iosHelper}${classEndAnchor}`);
    }
    iosConfig.modResults.contents = source;
    return iosConfig;
  });

  return config;
}

module.exports = createRunOncePlugin(
  withVoicePendingStoragePrivacy,
  'with-voice-pending-storage-privacy',
  '1.1.0',
);
