/**
 * Build-time: emit closed catalog ID enums for Zod + provider JSON schema.
 * Run: npx tsx scripts/build-catalog-id-enums.ts
 */
import { createRequire } from 'module';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { selectableArchetypeIds } from '../src/ai/catalogs/archetypeCatalog.v1.ts';
import { listMythicCatalogIds } from '../src/ai/catalogs/mythicNarrativeCatalog.ts';
import { buildDreamExtractionJsonSchemaObject } from '../src/ai/dreamExtractionJsonSchema.ts';

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'src/ai/catalogs/generated');
const OUT_FILE = path.join(OUT_DIR, 'catalogIdEnums.v1.ts');

function countTokens(text: string): { tokens: number; method: string } {
  try {
    const require = createRequire(import.meta.url);
    const candidates = [
      process.env.GPT_TOKENIZER_PATH,
      path.join('/tmp/tok/node_modules/gpt-tokenizer'),
      'gpt-tokenizer',
    ].filter(Boolean) as string[];
    for (const candidate of candidates) {
      try {
        const mod = require(candidate) as { encode: (s: string) => number[] };
        if (typeof mod.encode === 'function') {
          return { tokens: mod.encode(text).length, method: `gpt-tokenizer:${candidate}` };
        }
      } catch {
        // try next
      }
    }
  } catch {
    // fall through
  }
  return { tokens: Math.ceil(text.length / 4.2), method: 'char_estimate_/4.2' };
}

function main() {
  const archetypeIds = selectableArchetypeIds().slice().sort();
  const mythIds = listMythicCatalogIds().slice().sort();

  if (archetypeIds.length < 1) throw new Error('No selectable archetype ids');
  if (mythIds.length < 1) throw new Error('No myth catalog ids');

  const overlap = archetypeIds.filter((id) => mythIds.includes(id));
  if (overlap.length > 0) {
    throw new Error(`Archetype/myth id overlap forbidden: ${overlap.join(', ')}`);
  }

  const schemaObject = buildDreamExtractionJsonSchemaObject(archetypeIds, mythIds);
  const schemaJson = JSON.stringify(schemaObject);
  const schemaTokens = countTokens(schemaJson);

  mkdirSync(OUT_DIR, { recursive: true });

  const body = `/* AUTO-GENERATED by scripts/build-catalog-id-enums.ts — do not edit by hand. */
export const SELECTABLE_ARCHETYPE_IDS = ${JSON.stringify(archetypeIds, null, 2)} as const;
export const MYTH_CATALOG_IDS = ${JSON.stringify(mythIds, null, 2)} as const;

export type SelectableArchetypeId = (typeof SELECTABLE_ARCHETYPE_IDS)[number];
export type MythCatalogId = (typeof MYTH_CATALOG_IDS)[number];

export const SELECTABLE_ARCHETYPE_ID_COUNT = ${archetypeIds.length} as const;
export const MYTH_CATALOG_ID_COUNT = ${mythIds.length} as const;

/** Provider JSON schema serialized size (dream_extraction response_format). */
export const DREAM_EXTRACTION_JSON_SCHEMA_CHAR_COUNT = ${schemaJson.length} as const;
export const DREAM_EXTRACTION_JSON_SCHEMA_TOKEN_COUNT = ${schemaTokens.tokens} as const;
export const DREAM_EXTRACTION_JSON_SCHEMA_TOKEN_METHOD = ${JSON.stringify(schemaTokens.method)} as const;
`;

  writeFileSync(OUT_FILE, body, 'utf8');
  console.log(
    JSON.stringify(
      {
        outFile: OUT_FILE,
        archetypeIds: archetypeIds.length,
        mythIds: mythIds.length,
        schemaCharCount: schemaJson.length,
        schemaTokenCount: schemaTokens.tokens,
        schemaTokenMethod: schemaTokens.method,
      },
      null,
      2
    )
  );
}

main();
