-- Add immediate user-facing DreamDetail display distillation.
-- Long-term pattern metadata remains in the existing structured fields.
ALTER TABLE interpretations
  ADD COLUMN IF NOT EXISTS display_distillation jsonb DEFAULT null;

COMMENT ON COLUMN interpretations.display_distillation IS 'Minimal user-facing DreamDetail summary generated by AI extraction: essence, visible anchors, and movement line.';
